### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sfahadshahzad** [rmansillasoto/srtXcontrol#1]
Hi,

Hope you are doing well and keeping safe.

How I can build and test.

Regards,

Fahad

**Comment by rmansillasoto** [comment]
Hello!

Everything is fine thanks. Hope you're ok too.

I need to document the building process as well as translate to English the README. 

Thanks to you I have re checked the project and fixed some package dependencies problems that have appeared because of the time have past and new versions of some of them have changed.

I also updated the docker-compose.yml file. So for building the app you only need to run "docker-compose up --build"

Once the app is up and running you must use the url to interact with it via API with postman or insomnia, etc...

Hope it helps
Raúl.

**Comment by rmansillasoto** [comment]
Hello,

I also added some files for building ffprobe and srt containers.

Now everything should work fine...

Regards,
Raúl.

**Comment by rmansillasoto** [comment]
Hi, App containers are built automatically and are available in docker hub, so no need to build them. The only ones you should build are ffprobe and srt ones.
